//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innlevering3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ansatte
    {
        public int Id { get; set; }
        public string Fornavn { get; set; }
        public string Etternavn { get; set; }
        public int Mobil { get; set; }
        public string BildeSrc { get; set; }
        public int AvdelingId { get; set; }
        public int RolleId { get; set; }
    
        public virtual Avdeling Avdeling { get; set; }
        public virtual Rolle Rolle { get; set; }
    }
}
