//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innlevering3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avdeling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avdeling()
        {
            this.Ansatte = new HashSet<Ansatte>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
        public int Postnummer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ansatte> Ansatte { get; set; }
    }
}
