//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innlevering3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Henvendelser
    {
        public int Id { get; set; }
        public string Navn { get; set; }
        public string Epost { get; set; }
        public string Tittel { get; set; }
        public string Tekst { get; set; }
    }
}
