//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innlevering3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Innlevering3DatabaseEntities : DbContext
    {
        public Innlevering3DatabaseEntities()
            : base("name=Innlevering3DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ansatte> Ansatte { get; set; }
        public virtual DbSet<Avdeling> Avdeling { get; set; }
        public virtual DbSet<Henvendelser> Henvendelser { get; set; }
        public virtual DbSet<Rolle> Rolle { get; set; }
    }
}
